ProApp/urls.py
from django.contrib import admin
from django.urls import path 
from ProApp import views

urlpatterns = [
    #DASHBOARD
    path('dashboard' , views.dashboard, name="dashboard"),
    path('new_role' , views.new_role, name="new_role"),
    #log in/out
    path('login', views.user_login, name='login'),
    path('', views.user_login, name='login'),
    path('logout', views.user_logout, name='logout'),
    # project majaor
    path('projects' , views.projects, name="projects"),
    path('invoice' , views.invoice, name="invoice"),
    path('bom' , views.bom, name="bom"),
    path('vendor_list' , views.vendor_list, name="vendor_list"),
    path('vendor_price' , views.vendor_price, name="vendor_price"),
    path('po_list' , views.po_list, name="po_list"),
    path('po' , views.po, name="po"),
    #PROJECT list
    path('projects' , views.projects, name="projects"),
    path('newProject' , views.newProject, name="newProject"),
    path('edit_projects_desc/<int:projects_id>/' , views.edit_projects_desc , name="edit_projects_desc"),
    path('projects_desc/<int:projects_id>/' , views.projects_desc, name="projects_desc"), 
    path('project_detail/<int:project_id>/' , views.project_detail, name="project_detail"), 
    #User    
    path('users' , views.users , name="users"), 
    path('register', views.register, name='register'),
    path('users_desc/<int:user_id>/' , views.users_desc , name="users_desc"),
    path('edit_users_desc/<int:user_id>/', views.edit_users_desc, name='edit_users_desc'),
    #DELETE
    path('delete_user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('delete_project/<int:project_id>/', views.delete_project, name='delete_project'),
    path('delete_employee/<int:employee_id>/' , views.delete_employee , name="delete_employee"),
    path('delete_role/<int:role_id>/' , views.delete_role , name="delete_role"),
    #Employee
    path('employee' , views.employee , name="employee"),
    path('employee_register' , views.employee_register , name="employee_register"),
    path('edit_employee_desc/<int:employee_id>/' , views.edit_employee_desc , name="edit_employee_desc"),
    path('employee_desc/<int:employee_id>/' , views.employee_desc , name="employee_desc"),
    #Role
    path('new_role_edit/<int:role_id>/' , views.new_role_edit , name="new_role_edit"),
    path('new_role_desc/<int:role_id>' , views.new_role_desc , name="new_role_desc"),
    
    path('role' , views.role , name="role"),
    #Mapping
    path('mapping' , views.mapping , name="mapping"),
    path('id_assingment' , views.id_assingment , name="id_assingment"),

]

procurement/urls.py
from django.contrib import admin
from django.urls import path , include
from  ProApp import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ProApp.urls')),
    
]

ProApp/models.py
from django.db import models
from django.contrib.auth.models import User

from django.core.validators import MinValueValidator
# Create your models here.


class Project(models.Model):
    project_code = models.CharField(max_length=25 ,blank=True)
    project_name = models.CharField(max_length=255 , blank=True)
    customer = models.CharField(max_length=255 ,blank=True)
    end_user = models.CharField(max_length=255, blank=True)

    # SO Currency (Dropdown s   election)
    CURRENCY_CHOICES = (
        ('', 'Select Currency'),
        ('SAR', 'Saudi Riyal (SAR)'),
        ('PKR', 'Pakistani Rupee (PKR)'),
        ('USD', 'US Dollar (USD)'),
        # Add more currencies as needed
    )
    project_currency = models.CharField(max_length=3, choices=CURRENCY_CHOICES, default='')

    # Set a default value for currency_rate (e.g., 1.00 for USD)
    currency_rate = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(0.01)], default=1.00)
    payment_terms = models.PositiveIntegerField(validators=[MinValueValidator(1)] , default=1)  # Minimum payment terms: 1 day

    project_manager = models.CharField(max_length=255 ,blank=True)
    company = models.CharField(max_length=255, blank=True)
    address_line_1 = models.CharField(max_length=255, blank=True)
    address_line_2 = models.CharField(max_length=255, blank=True)
    mobile = models.CharField(max_length=20, blank=True)
    email = models.EmailField(blank=True)

    # Monetary fields (consider using a separate model for better organization)
    initial_so_value = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    change_order_1 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, default=0.00)
    change_order_2 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, default=0.00)
    change_order_3 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, default=0.00)
    change_order_4 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, default=0.00)
    total_so = models.DecimalField(max_digits=10, decimal_places=2, blank=True, default=0.00)

    bid_bom_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    bid_cogs = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    bid_va = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

    design_cogs = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    design_va = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

    running_cogs = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    running_va = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

    def __str__(self):
        return self.project_code + " - " + self.project_name





# class Project(models.Model):
#     code = models.CharField(max_length=225, default="1" , unique=True)
#     projectName = models.CharField(max_length=225, default="1")
#     projectDesc = models.TextField(max_length=225, default="1")
#     DateOfStart = models.DateField(blank=True, null=True)  # Adjust the default date as needed
#     DateOfEnd = models.DateField(blank=True, null=True)    # Adjust the default date as needed
#     projectValue = models.FloatField(default=1.0)

#     def __str__(self):
#         return self.projectName    
    
class Employee(models.Model):
    Fullname = models.CharField(default="", max_length=20)
    adress = models.CharField(default="", max_length=20)
    service = models.CharField(default="" , max_length=225)         
    Email = models.EmailField(default="")
    
    def __str__(self):
        return str(self.Fullname)       
      
class Role(models.Model):
    
    GROUP_HR_EMPLOYEE = 'HR'
    GROUP_Procurement = 'Procurement'
    GROUP_Marketing = 'Marketing'
    GROUP_Administrative = 'Administrative'
    GROUP_CHOICES = [
        (GROUP_HR_EMPLOYEE, 'HR'),
        (GROUP_Procurement, 'Procurement'),
        (GROUP_Marketing, 'Marketing'),
        (GROUP_Administrative, 'Administrative'),
    ]
    
    role_name = models.CharField(max_length=255, unique=True)
    group = models.CharField(max_length=22 , choices=GROUP_CHOICES)
    full_access = models.BooleanField(default=False)
    can_view_projects = models.BooleanField(default=False)
    can_edit_projects = models.BooleanField(default=False)
    can_view_employee = models.BooleanField(default=False)
    can_edit_employee = models.BooleanField(default=False)
    can_view_users = models.BooleanField(default=False)
    can_edit_users = models.BooleanField(default=False)
    
    def __str__(self):
        return self.role_name    
    
class UserProfile(models.Model):
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.ForeignKey( Role , on_delete=models.CASCADE)
    employeeID = models.OneToOneField(Employee, default="" , on_delete=models.CASCADE)
    
    #Status = models.BooleanField(default="")

    def __str__(self):
        return str(self.user)
    
class UserEmployeeMapping(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user', 'employee')    


class PageView(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True)

templates/role/admin_dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

      <!-- Counts Section -->
      <section class="py-5">
        <div class="container-fluid">
          <div class="row">
            <!-- Count item widget-->
            <div class="col-xl-2 col-md-4 col-6 gy-4 gy-xl-0">
              <div class="d-flex">
                <svg class="svg-icon svg-icon-sm svg-icon-heavy text-primary mt-1 flex-shrink-0">
                  <use xlink:href="#user-1"> </use>
                </svg>
                <div class="ms-2">
                  <h3 class="h4 text-dark text-uppercase fw-normal">New Clients</h3>
                  <p class="text-gray-500 small">Last 7 days</p>
                  <p class="display-6 mb-0">25</p>
                </div>
              </div>
            </div>
            <!-- Count item widget-->
            <div class="col-xl-2 col-md-4 col-6 gy-4 gy-xl-0">
              <div class="d-flex">
                <svg class="svg-icon svg-icon-sm svg-icon-heavy text-primary mt-1 flex-shrink-0">
                  <use xlink:href="#survey-1"> </use>
                </svg>
                <div class="ms-2">
                  <h3 class="h4 text-dark text-uppercase fw-normal">Work Orders</h3>
                  <p class="text-gray-500 small">Last 5 days</p>
                  <p class="display-6 mb-0">400</p>
                </div>
              </div>
            </div>
            <!-- Count item widget-->
            <div class="col-xl-2 col-md-4 col-6 gy-4 gy-xl-0">
              <div class="d-flex">
                <svg class="svg-icon svg-icon-sm svg-icon-heavy text-primary mt-1 flex-shrink-0">
                  <use xlink:href="#list-details-1"> </use>
                </svg>
                <div class="ms-2">
                  <h3 class="h4 text-dark text-uppercase fw-normal">New Quotes</h3>
                  <p class="text-gray-500 small">Last 2 months</p>
                  <p class="display-6 mb-0">342</p>
                </div>
              </div>
            </div>
            <!-- Count item widget-->
            <div class="col-xl-2 col-md-4 col-6 gy-4 gy-xl-0">
              <div class="d-flex">
                <svg class="svg-icon svg-icon-sm svg-icon-heavy text-primary mt-1 flex-shrink-0">
                  <use xlink:href="#numbers-1"> </use>
                </svg>
                <div class="ms-2">
                  <h3 class="h4 text-dark text-uppercase fw-normal">New Invoices</h3>
                  <p class="text-gray-500 small">Last 2 days</p>
                  <p class="display-6 mb-0">123</p>
                </div>
              </div>
            </div>
            <!-- Count item widget-->
            <div class="col-xl-2 col-md-4 col-6 gy-4 gy-xl-0">
              <div class="d-flex">
                <svg class="svg-icon svg-icon-sm svg-icon-heavy text-primary mt-1 flex-shrink-0">
                  <use xlink:href="#literature-1"> </use>
                </svg>
                <div class="ms-2">
                  <h3 class="h4 text-dark text-uppercase fw-normal">Open Cases</h3>
                  <p class="text-gray-500 small">Last 3 months</p>
                  <p class="display-6 mb-0">92</p>
                </div>
              </div>
            </div>
            <!-- Count item widget-->
            <div class="col-xl-2 col-md-4 col-6 gy-4 gy-xl-0">
              <div class="d-flex">
                <svg class="svg-icon svg-icon-sm svg-icon-heavy text-primary mt-1 flex-shrink-0">
                  <use xlink:href="#paper-stack-1"> </use>
                </svg>
                <div class="ms-2">
                  <h3 class="h4 text-dark text-uppercase fw-normal">New Cases</h3>
                  <p class="text-gray-500 small">Last 7 days</p>
                  <p class="display-6 mb-0">70</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <!-- Header Section-->
      <section class="bg-white py-5">
        <div class="container-fluid">
          <div class="row d-flex align-items-md-stretch">
            <!-- To Do List-->
            <div class="col-lg-3 col-md-6">
              <div class="card shadow-0">
                <div class="card-body p-0">
                  <h2 class="h3 fw-normal">To do List</h2>
                  <p class="text-sm text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                  <form>
                    <div class="form-check">
                      <input class="form-check-input" type="checkbox" id="list1">
                      <label class="form-check-label text-sm" for="list1">Similique sunt in culpa qui officia</label>
                    </div>
                    <div class="form-check">
                      <input class="form-check-input" type="checkbox" id="list2">
                      <label class="form-check-label text-sm" for="list2">Ed ut perspiciatis unde omnis iste</label>
                    </div>
                    <div class="form-check">
                      <input class="form-check-input" type="checkbox" id="list3">
                      <label class="form-check-label text-sm" for="list3">At vero eos et accusamus et iusto </label>
                    </div>
                    <div class="form-check">
                      <input class="form-check-input" type="checkbox" id="list4">
                      <label class="form-check-label text-sm" for="list4">Explicabo Nemo ipsam voluptatem</label>
                    </div>
                    <div class="form-check">
                      <input class="form-check-input" type="checkbox" id="list5">
                      <label class="form-check-label text-sm" for="list5">Similique sunt in culpa qui officia</label>
                    </div>
                    <div class="form-check">
                      <input class="form-check-input" type="checkbox" id="list6">
                      <label class="form-check-label text-sm" for="list6">At vero eos et accusamus et iusto</label>
                    </div>
                    <div class="form-check">
                      <input class="form-check-input" type="checkbox" id="list7">
                      <label class="form-check-label text-sm" for="list7">Similique sunt in culpa qui officia</label>
                    </div>
                    <div class="form-check">
                      <input class="form-check-input" type="checkbox" id="list8">
                      <label class="form-check-label text-sm" for="list8">Ed ut perspiciatis unde omnis iste</label>
                    </div>
                  </form>
                </div>
              </div>
            </div>
            <!-- Pie Chart-->
            <div class="col-lg-3 col-md-6">
              <div class="card shadow-0">
                <h2 class="h3 fw-normal">Project Beta progress</h2>
                <p class="text-sm text-muted"> Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                <div class="pie-chart">
                  <canvas id="pieChart" style="width: 300px; height: 300px; max-width: 100%"> </canvas>
                </div>
              </div>
            </div>
            <!-- Line Chart -->
            <div class="col-lg-6 col-md-12">
              <div class="card shadow-0">
                <h2 class="h3 fw-normal">Sales marketing report</h2>
                <p class="text-sm text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolor amet officiis</p>
                <canvas id="lineCahrt"></canvas>
              </div>
            </div>
          </div>
        </div>
      </section>
      <!-- Statistics Section-->
      <section class="py-5">
        <div class="container-fluid">
          <div class="row align-items-stretch gy-4">
            <div class="col-lg-4">
              <!-- Income-->
              <div class="card text-center h-100 mb-0">
                <div class="card-body">
                  <svg class="svg-icon svg-icon-big svg-icon-light mb-4 text-muted">
                    <use xlink:href="{% static '#sales-up-1' %} "> </use>
                  </svg>
                  <p class="text-gray-700 display-6">126,418</p>
                  <p class="text-primary h2 fw-bold">All Income</p>
                  <p class="text-xs text-gray-600 mb-0">Lorem ipsum dolor sit amet, consectetur adipisicing elit sed do.</p>
                </div>
              </div>
            </div>
            <div class="col-lg-4">
              <!-- Monthly Usage-->
              <div class="card h-100 mb-0">
                <div class="card-body">
                  <h2 class="h3 fw-normal mb-4">Monthly Usage</h2>
                  <div class="row align-items-center mb-3 gx-lg-5">
                    <div class="col-lg-6">
                      <table class="w-100">
                        <tbody>
                          <tr>
                            <td>
                              <div class="position-relative mx-auto" style="max-width: 120px">
                                <canvas class="mx-auto" id="monthlyProgress" width="150" height="150"></canvas>
                                <p class="h3 text-primary fw-normal position-absolute top-50 start-50 translate-middle text-center m-0">80%</p>
                              </div>
                            </td>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                    <div class="col-lg-6 border-start">
                      <p class="fw-bold h2 text-primary">80.56 Gb</p>
                      <p class="text-xs fw-light text-gray-500 mb-0">Current Plan</p>
                      <p class="text-gray-500">100 Gb Monthly</p>
                    </div>
                  </div>
                  <p class="text-xs text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing.</p>
                </div>
              </div>
            </div>
            <div class="col-lg-4">
              <!-- User Actibity-->
              <div class="card h-100 mb-0">
                <div class="card-body">
                  <h2 class="h3 fw-normal mb-4">User Activity</h2>
                  <p class="display-6">210</p>
                  <h3 class="h4 fw-normal">Social Users</h3>
                  <div class="progress rounded-0 mb-3">
                    <div class="progress-bar progress-bar bg-primary" role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                  <div class="d-flex justify-content-between">
                    <div class="text-start">
                      <p class="h5 fw-normal mb-2">Pages Visits</p>
                      <p class="fw-bold text-xl text-primary mb-0">{{ total_views }}</p>
                    </div>
                    <div class="text-end">
                      <p class="h5 fw-normal mb-2">New Visits</p>
                      <p class="fw-bold text-xl text-primary mb-0">73.4%</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
     
{% endblock %}

templates/role/edit_projects_desc.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

  <!-- Breadcrumb-->
  <div class="bg-gray-200 text-sm">
    <div class="container-fluid">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb mb-0 py-3">
            <li class="breadcrumb-item"><a class="fw-light" href="/dashboard">Home</a></li>
            <li class="breadcrumb-item fw-light" aria-current="page"><a class="fw-light" href="{% url 'projects' %}">Project</a> </li>
            <li class="breadcrumb-item fw-light" aria-current="page"><a class="fw-light" href="{% url 'projects_desc' project.id %}">Project Desc</a></li>
          <li class="breadcrumb-item active fw-light" aria-current="page">Project Edit</li>
        </ol>
      </nav>
    </div>
  </div>

  <div class="container-fluid">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-header border-bottom">
        <h3 class="h4 mb-0">{{ project.projectName }}</h3>
      </div>
      <div class="card-body">
        <p class="text-sm">Change your form setting here.</p>
        <form method="post" action="{% url 'edit_projects_desc' project.id %}">
            {% csrf_token %}
          <div class="mb-3">
            <label class="form-label" for="exampleInputEmail1">This time Project name: </label> {{ project.project_name }} <br>
            <input type="hidden" name="user_id" value="{{ user.id }}">
             Change it from here:  {{ form.project_name }}
          </div>

          <div class="mb-4">
            <label class="form-label" for="id_project_code">The Project Code is: </label>
            {{ project.project_code }}<br>
            <label for="id_project_code">Change it from here:</label>
            {{ form.project_code }}
          </div>

          <div class="mb-3">
            <label class="form-label" for="exampleInputPassword1">The Customer is : </label> {{project.customer}}<br>
            Change it from here: {{ form.customer}}
          </div>

          <div class="mb-3">
            <label class="form-label"for="exampleInputPassword1">The End User is: </label> {{project.end_user}}<br>
            Change it from here: {{ form.end_user}}
          </div>
          <div class="mb-3">
            <label class="form-label" for="exampleInputPassword1">project_currency : </label> {{project.project_currency}}<br>
            Change it from here: {{ form.project_currency}}
          </div>
         

          <div class="mb-3">
            <label class="form-label" for="exampleInputPassword1">The Currency Rate is : </label> {{project.currency_rate}}<br>
            Change it from here: {{ form.currency_rate}}
          </div>

          <div class="mb-3">
            <label class="form-label" for="exampleInputPassword1">The payment terms is : </label> {{project.payment_terms}}<br>
            change it from here:   {{ form.payment_terms}}
          </div>

          <div class="mb-3">
            <label class="form-label" for="exampleInputPassword1">The Project Manager is : </label> {{project.project_manager}}<br>
            Change it from here: {{ form.project_manager}}
          </div>

          <div class="mb-3">
            <label class="form-label" for="exampleInputPassword1">The Company is : </label> {{project.company}}<br>
            Change it from here: {{ form.company}}
          </div>

          <div class="mb-3">
            <label class="form-label" for="exampleInputPassword1">The Address line 1 is : </label> {{project.address_line_1}}<br>
            Change it from here:{{ form.address_line_1}}
          </div>

          <div class="mb-3">
            <label class="form-label" for="exampleInputPassword1">The Address line 2 is : </label> {{project.address_line_2}}<br>
            Change it from here: {{ form.address_line_2}}
          </div>

          <div class="mb-3">
            <label class="form-label" for="exampleInputPassword1">The Mobile number is : </label> {{project.mobile}}<br>
            Change it from here: {{ form.mobile}}
          </div>
          
          <div class="mb-3">
            <label class="form-label" for="exampleInputPassword1">The Email is: </label> {{project.email}}<br>
            Change it from here: {{ form.email}}
          </div>

          <div class="mb-3">
            <label class="form-label" for="exampleInputPassword1">The initial SO value is: </label> {{project.initial_so_value}}<br>
            Change it from here: {{ form.initial_so_value}}
          </div>

          <div class="mb-3">
            <label class="form-label" for="exampleInputPassword1">The Change Order 1 is: </label> {{project.change_order_1}}<br>
            Change it from here:  {{ form.change_order_1}}
          </div>

          <div class="mb-3">
            <label class="form-label" for="exampleInputPassword1">The Change Order 2 is: </label> {{project.change_order_2}}<br>
            Change it from here: {{ form.change_order_2}}
          </div>

          <div class="mb-3">
            <label class="form-label" for="exampleInputPassword1">The Change Order 3 is: </label> {{project.change_order_3}}<br>
            Change it from here: {{ form.change_order_3}}
          </div>

          <div class="mb-3">
            <label class="form-label" for="exampleInputPassword1">The Change Order 4 is: </label> {{project.change_order_4}}<br>
            Change it from here: {{ form.change_order_4}}
          </div>

          <div class="mb-3">
            <label class="form-label" for="exampleInputPassword1">The TotalSO is: </label> {{project.total_so}}<br>
            Change it from here: {{ form.total_so}}
          </div>

          <div class="mb-3">
            <label class="form-label" for="exampleInputPassword1">The Bid BOM Price is: </label> {{project.bid_bom_price}}<br>
            Change it from here: {{ form.bid_bom_price}}
          </div>

          <div class="mb-3">
            <label class="form-label" for="exampleInputPassword1">The Bid Cogs is: </label> {{project.bid_cogs}}<br>
            Change it from here:  {{ form.bid_cogs}}
          </div>

          <div class="mb-3">
            <label class="form-label" for="exampleInputPassword1">The Bid VA is: </label> {{project.bid_va}}<br>
            Change it from here: {{ form.bid_va}}
          </div>

          <div class="mb-3">
            <label class="form-label" for="exampleInputPassword1">The Design Cogs is: </label> {{project.design_cogs}}<br>
            Change it from here: {{ form.design_cogs}}
          </div>

          <div class="mb-3">
            <label class="form-label" for="exampleInputPassword1">The Design VA is: </label> {{project.design_va}}<br>
            Change it from here: {{ form.design_va}}
          </div>
          <div class="mb-3">
            <label class="form-label" for="exampleInputPassword1">The Running Cogs is : </label> {{project.running_cogs}}<br>
            Change it from here:  {{ form.running_cogs}}
          </div>
          <div class="mb-3">
            <label class="form-label" for="exampleInputPassword1">The Running VA is : </label> {{project.running_va}}<br>
            Change it from here: {{ form.running_va}}
          </div>
         <button class="btn btn-primary"  type="submit">Submit</button>
        </form>
      </div>
    </div>
  </div>
</div>


{% endblock %}

templates/role/edit_users_desc.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

 
        <div class="bg-gray-200 text-sm">
            <div class="container-fluid">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb mb-0 py-3">
                <li class="breadcrumb-item"><a class="fw-light" href="/dashboard">Home</a></li>
                <li class="breadcrumb-item fw-light" aria-current="page"><a class="fw-light" href="{% url 'users' %}">Users pages</a> </li>
                <li class="breadcrumb-item active fw-light" aria-current="page">user Desc</li>
                </ol>
            </nav>
            </div>
        </div>


        <section class="tables">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header border-bottom">
                            <div class="row align-items-center">
                                <div class="col-md-6">
                                <h3 class="h4 mb-0">Projects Data Table</h3>
                                </div>
                                {% if user.userprofile.role.can_edit_users or user.userprofile.role.full_access%}
                                    <div class="col-md-6 text-md-end"> 
                                
                                        
                                        <form method="post" action="{% url 'delete_user' user.id %}">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-danger">Delete</button>
                                        </form>
                                        <br>
                                        <a href= {% url 'users_desc' user.id %} class="btn btn-success">Edit</a>      
                                    </div>
                                {% endif %}
                            </div>
                            </div>
                            <div class="card-body">
                                <div class="col-md-12">
                                    <!-- Project Information -->
                                    <dl class="row">
                                        <dt class="col-sm-4">User Name:</dt>
                                        <dd class="col-sm-8"><strong>{{user.username}}</strong></dd>
<hr>
                                        <dt class="col-sm-4">User employee ID :</dt>
                                        <dd class="col-sm-8">{{ user.userprofile.employeeID }}</dd>
                    <hr>
                                        <dt class="col-sm-4">User Role : </dt>
                                        <dd class="col-sm-8">{{ user.userprofile.role }}</dd>
                    <hr>
                                        <dt class="col-sm-4">User Group :</dt>
                                        <dd class="col-sm-8">{{ user.userprofile.role.group }}</dd>
                                    </dl>
                                </div>
                            </div>
                        </div>
                    </div>
               </div>
            </div>
        </section>                            


{% endblock %}